# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TCMainView.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMainView(object):
    def setupUi(self, frmMainView):
        frmMainView.setObjectName("frmMainView")
        frmMainView.resize(434, 472)
        frmMainView.setMinimumSize(QtCore.QSize(434, 472))
        frmMainView.setMaximumSize(QtCore.QSize(434, 472))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        frmMainView.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/icon/graph1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmMainView.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(frmMainView)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.horizontalLayoutWidget.setFont(font)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.headerLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.headerLayout.setContentsMargins(0, 0, 0, 0)
        self.headerLayout.setObjectName("headerLayout")
        self.txtPath = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.txtPath.setFont(font)
        self.txtPath.setReadOnly(True)
        self.txtPath.setObjectName("txtPath")
        self.headerLayout.addWidget(self.txtPath)
        self.btnFileSelect = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.btnFileSelect.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/icon/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFileSelect.setIcon(icon1)
        self.btnFileSelect.setObjectName("btnFileSelect")
        self.headerLayout.addWidget(self.btnFileSelect)
        self.btnFolderSelect = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.btnFolderSelect.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/icon/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFolderSelect.setIcon(icon2)
        self.btnFolderSelect.setObjectName("btnFolderSelect")
        self.headerLayout.addWidget(self.btnFolderSelect)
        self.btnGraphDisplay = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.btnGraphDisplay.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/icon/graph2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGraphDisplay.setIcon(icon3)
        self.btnGraphDisplay.setObjectName("btnGraphDisplay")
        self.headerLayout.addWidget(self.btnGraphDisplay)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(frmMainView)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 411, 311))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.horizontalLayoutWidget_2.setFont(font)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.mainImageLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.mainImageLayout.setContentsMargins(0, 0, 0, 0)
        self.mainImageLayout.setObjectName("mainImageLayout")
        self.viewMainImage = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.viewMainImage.setFont(font)
        self.viewMainImage.setObjectName("viewMainImage")
        self.mainImageLayout.addWidget(self.viewMainImage)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(frmMainView)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 380, 411, 80))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.horizontalLayoutWidget_3.setFont(font)
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.subImageLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.subImageLayout.setContentsMargins(0, 0, 0, 0)
        self.subImageLayout.setObjectName("subImageLayout")
        self.viewMiniImage1 = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.viewMiniImage1.setFont(font)
        self.viewMiniImage1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.viewMiniImage1.setObjectName("viewMiniImage1")
        self.subImageLayout.addWidget(self.viewMiniImage1)
        self.viewMiniImage2 = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.viewMiniImage2.setFont(font)
        self.viewMiniImage2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.viewMiniImage2.setObjectName("viewMiniImage2")
        self.subImageLayout.addWidget(self.viewMiniImage2)
        self.viewMiniImage3 = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.viewMiniImage3.setFont(font)
        self.viewMiniImage3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.viewMiniImage3.setObjectName("viewMiniImage3")
        self.subImageLayout.addWidget(self.viewMiniImage3)
        self.viewMiniImage4 = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.viewMiniImage4.setFont(font)
        self.viewMiniImage4.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.viewMiniImage4.setObjectName("viewMiniImage4")
        self.subImageLayout.addWidget(self.viewMiniImage4)
        self.viewMiniImage5 = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        self.viewMiniImage5.setFont(font)
        self.viewMiniImage5.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.viewMiniImage5.setObjectName("viewMiniImage5")
        self.subImageLayout.addWidget(self.viewMiniImage5)

        self.retranslateUi(frmMainView)
        self.btnFileSelect.clicked.connect(frmMainView.file_select_click)
        self.btnFolderSelect.clicked.connect(frmMainView.folder_select_click)
        self.btnGraphDisplay.clicked.connect(frmMainView.graph_display_click)
        QtCore.QMetaObject.connectSlotsByName(frmMainView)

    def retranslateUi(self, frmMainView):
        _translate = QtCore.QCoreApplication.translate
        frmMainView.setWindowTitle(_translate("frmMainView", "TrendChecker - Main"))
        self.btnFileSelect.setText(_translate("frmMainView", "ファイル選択"))
        self.btnFolderSelect.setText(_translate("frmMainView", "フォルダ選択"))
        self.btnGraphDisplay.setText(_translate("frmMainView", "グラフ表示"))

